apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kserve-crd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kserve.github.io/kserve
    chart: kserve-crd
    targetRevision: v0.15.2
    helm:
      releaseName: kserve-crd
  destination:
    server: https://kubernetes.default.svc
    namespace: kserve
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
