apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spire
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://spiffe.github.io/helm-charts-hardened
      chart: spire
      targetRevision: 0.24.1
      helm:
        releaseName: spire
        valueFiles:
          - $values/demo/gitops/values/spire-values.yaml
    - repoURL: https://github.com/peopleforrester/LLMday-Texas-2026
      targetRevision: staging
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: spire-system
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
