apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tetragon
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.cilium.io
      chart: tetragon
      targetRevision: 1.7.0
      helm:
        releaseName: tetragon
        valueFiles:
          - $values/demo/gitops/values/tetragon-values.yaml
    - repoURL: https://github.com/peopleforrester/LLMday-Texas-2026
      targetRevision: staging
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: tetragon
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
