apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admission
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/peopleforrester/LLMday-Texas-2026
    path: demo/gitops/manifests/vap
    targetRevision: staging
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [ServerSideApply=true]
