apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-server
  namespace: staging
  labels:
    app: model-server
    app.kubernetes.io/managed-by: mlops-pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-server
  template:
    metadata:
      labels:
        app: model-server
    spec:
      containers:
      - name: model-server
        image: nginx:1.27-alpine
        ports:
        - containerPort: 80
