allInOne:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
storage:
  type: memory
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
provisionDataStore:
  cassandra: false
  elasticsearch: false
  kafka: false
