kserve:
  controller:
    deploymentMode: RawDeployment
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
  agent:
    image: kserve/agent
  storageInitializer:
    image: kserve/storage-initializer
